add vue
Statismic/workspace pull request #22
Opened 2019-03-01 04:05 UTC by xiajohn

2019-03-01 19:01 UTC, lherman-cs requested changes

2019-03-01 19:01 UTC, lherman-cs commented on jxia/index.html
> +        <d>Sample Mean:</d> <br><input type="text" name="Sample Mean" value=""><br>
`d` is not a valid html tag. Please fix this and the other `d`s

2019-03-01 19:05 UTC, lherman-cs requested changes

2019-03-01 19:05 UTC, lherman-cs commented on jxia/index.html
> +  background-image: url('/images/confidenceInterval.jpg');
This should be a relative path, `./images/confidenceInterval.jpg`. Also, probably remove this since the background image seems distracting.

2019-03-01 20:24 UTC, xiajohn commented
do changes

2019-03-01 20:47 UTC, xiajohn commented
gaby

2019-03-02 16:27 UTC, gherman-cs requested changes

2019-03-02 16:27 UTC, gestewa commented on jxia/index.html
> +  d {
REMOVE UNUSED CODE
aside from that d is poor naming conventions

2019-03-02 16:27 UTC, gestewa commented on jxia/index.html
> +        message: 'helo',
REMOVE UNUSED CODE
unused variable

2019-03-02 16:27 UTC, gestewa commented on jxia/index.html
> +        myAlert() {
REMOVE UNUSED CODE
myAlert()

2019-03-02 16:27 UTC, gestewa commented on jxia/index.html
> +        myAlert2() {
REMOVE UNUSED CODE
myAlert2()

2019-03-02 16:27 UTC, gestewa commented on jxia/index.html
> +      <img src="images/confidence.png" alt="Flowers in Chania" width="80%" height="40%">
"Flowers in Chania"
???
Do you know what an alt tag does?

2019-03-04 21:07 UTC, xiajohn reviewed
fixed

2019-03-06 03:26 UTC, gestewa commented on jxia/index.html
> +  background: url(http://apod.nasa.gov/apod/image/0603/coma_misti.jpg) -80px -80px;
We think this is distracting, and not matching our theme, we recommend reviewing it to aid in website cohesion

2019-03-06 03:28 UTC, gherman-cs requested changes
Fix the d tags, recommend removing the 'nasa' image

2019-03-07 16:59 UTC, merged