Vue Implementation of Analyze Button
Statismic/workspace pull request #26
Opened 2019-03-01 18:09 UTC by sangrak8589

changed my button so that it is now formatted with view and gives an … alert of what the button is doing upon click

2019-03-01 19:40 UTC, lherman-cs submitted a review, later dismissed

2019-03-01 19:40 UTC, lherman-cs commented on sangrak/index.html
> +    <body>
you should only have 1 `body`

2019-03-01 19:40 UTC, lherman-cs commented on sangrak/index.html
> +        <script src="https://cdn.jsdelivr.net/npm/vue/dist/vue.js"></script>
please move this line and the next `<script>` to the very end in the `body` tag

2019-03-02 16:36 UTC, gestewa commented on sangrak/index.html
> +    <style>
Hey, since we are using vue, lets move style to be in a separate block like in the form example, it looks cleaner

2019-03-02 16:38 UTC, gestewa commented on sangrak/index.html
>                  <form action="/action_page.php">
Hey, we are not using php at all, remove ALL references to php

additionally you dont have an action page .php 

aside from that "/action_page.php" starts from the root directory, we want "./blah.php"

2019-03-02 16:40 UTC, gestewa commented on sangrak/index.html
> +        <script src="https://cdn.jsdelivr.net/npm/vue/dist/vue.js"></script>
for the same reason, we are factoring out our css, we want clean looking code, it is more readable

2019-03-02 16:41 UTC, gherman-cs submitted a review, later dismissed
make changes according to the comments

2019-03-08 22:25 UTC, sangrak8589 commented on sangrak/index.html
>                  <form action="/action_page.php">
resolved

2019-03-12 20:44 UTC, lherman-cs requested changes
The analyze button somehow still doesn't give an alert.

2019-03-15 03:47 UTC, sangrak8589 commented
what do you mean? When you hit analyze a pop up alert shows up

2019-03-15 16:17 UTC, lherman-cs commented
@sangrak8589 feel free to check my tool here: https://review.lukas-coding.us/. This tool helps to actually see your PR. 

PR number: 26
Repo's url: https://github.com/Statismic/workspace.git

2019-03-17 00:48 UTC, gestewa commented
Were working on getting your grades in canvas up to speed, and reviewing the PR, the grades that were just put in were not necessarily 100% accurate.

2019-03-21 21:31 UTC, sangrak8589 commented
analyze button is working now with VUE implementation and gives alert

2019-03-21 21:32 UTC, sangrak8589 commented
> The analyze button somehow still doesn't give an alert.

It is now working

2019-03-29 00:50 UTC, lherman-cs commented
@sangrak8589 I just reviewed your PR. The button seems not working anymore. Also, it is not responsive yet. Below is the screenshot of your page when it's in a small screen.

![Screenshot_2019-03-28_20-51-36](https://user-images.githubusercontent.com/15654932/55201813-28ee5700-519b-11e9-91ce-85d3e5a568e9.png)

2019-03-29 00:52 UTC, lherman-cs commented
@sangrak8589 also, please always double check your work with https://review.lukas-coding.us/. Because, when you're developing, you might forget that the root path of the project is **not** in your directory, but 1 level higher.

2019-03-29 03:49 UTC, sangrak8589 commented
Idk why the button isn't working when you look at it. I showed you in Mcadam's two said ago that it was working and you double checked it and said it was too using the PR number.

2019-03-29 03:58 UTC, sangrak8589 commented
Ohhh, i think i see the mistake you're making. So in the screenshot below, the one on the right is the index.html file that I updated over spring break and the button and CSS media queries are done and completed correctly. And as you can see from your https://review.lukas-coding.us/.  repos they do work correctly. I think you were looking at some old file, (on the left) in the screenshot below.

<img width="1280" alt="Screen Shot 2019-03-28 at 11 55 53 PM" src="https://user-images.githubusercontent.com/35939739/55208654-5a741c00-51b5-11e9-903c-956a6e581a60.png">

2019-03-29 19:57 UTC, gherman-cs approved these changes

2019-03-29 19:57 UTC, merged